### ISSUE TITLE
Issue with feature pre-calculation

### ISSUE THREAD

**Issue by remcginn357** [huangzhii/nuclei.io#7]
When I run the feature pre-calculation I get the following error: 
line 664, in _get_delaunay_graph_stat_parallel
    mat_delaunay.append(self._delaunay_parallel(id, update_n=1))
TypeError: SlideProperty._delaunay_parallel() got an unexpected keyword argument 'update_n'

I get this error using the CMU-1 example image and when I use one of my own .svs images

**Comment by huangzhii** [comment]
will fix soon, thanks!

**Comment by Gaotianhong** [comment]
The same issue😭😭

**Comment by huangzhii** [comment]
Hi @remcginn357 @Gaotianhong , the repo has a recent update. Have you tried the latest main branch? Use `git pull` to get the latest code base should solve the issue.

**Comment by Gaotianhong** [comment]
Hi @huangzhii , I have pulled the latest code, but the issue still persists. I suspect the issue might be related to parameter passing in the `nuc_stat.py` file. Specifically, on line 664, there are two arguments being passed:

```python
mat_delaunay.append(self._delaunay_parallel(id, update_n=1))
```

However, on line 558, the `_delaunay_parallel` function only accepts one argument:

```python
def _delaunay_parallel(self, i):
```

Could this be the cause of the issue?

**Comment by huangzhii** [comment]
Okay just fixed it. can you try it again?

https://github.com/huangzhii/nuclei.io/commit/52ddc08c6a7138078136c18573b6887a9373b390#diff-c55138bbd7bd4c571df8828b2858b54db4dfaae38d93e949a45baecdf83f9c9eR562

**Comment by Gaotianhong** [comment]
@huangzhii Worked successfully, thank you!
